"""Seed script: loads the real, complete application history from Indeed,
Glassdoor, Jobright.ai, and LinkedIn exports, plus a few roles tracked only
in conversation (FDM, Welcome Centre Shelter, CRA). Compiled 2026-10-04."""
from .database import init_db, get_conn
from . import crud

DEMO = [
    dict(company="Centoco Plastics Limited", role="General Labourer (Part-time)", status="rejected",
         date_applied="2026-09-26", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Leap Physiotherapy", role="Office Administrator", status="rejected",
         date_applied="2026-09-26", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Ottawa Senators", role="IT Support Analyst", status="rejected",
         date_applied="2026-09-26", resume_version=None,
         location="Kanata, ON", source="Indeed"),
    dict(company="Universal Fabricating Inc.", role="IT Support Specialist", status="rejected",
         date_applied="2026-09-23", resume_version=None,
         location="Kingsville, ON", source="Indeed"),
    dict(company="Mirus International Inc.", role="Electrical Engineering Technologist", status="rejected",
         date_applied="2026-09-23", resume_version=None,
         location="Brampton, ON", source="Indeed"),
    dict(company="Scentroid (division of Ides Canada Inc.)", role="Technical Support Engineer", status="rejected",
         date_applied="2026-09-23", resume_version=None,
         location="Stouffville, ON", source="Indeed"),
    dict(company="Columbia Forest Products", role="Enterprise Technology Analyst", status="rejected",
         date_applied="2026-09-23", resume_version=None,
         location="Hearst, ON", source="Glassdoor"),
    dict(company="Achev", role="IT - Business Analyst - Level 1", status="rejected",
         date_applied="2026-09-23", resume_version=None,
         location="Mississauga, ON", source="Glassdoor"),
    dict(company="PACT", role="BI Analyst", status="rejected",
         date_applied="2026-09-21", resume_version=None,
         location="Mississauga, ON", source="Glassdoor"),
    dict(company="Ainsworth Inc.", role="Data Analyst (Contract, 6 months)", status="rejected",
         date_applied="2026-09-21", resume_version=None,
         location="Mississauga, ON", source="Glassdoor"),
    dict(company="Aro ic", role="Reporting & Data Analyst (SQL / Python / Power BI)", status="rejected",
         date_applied="2026-09-18", resume_version=None,
         location="Markham, ON", source="Indeed"),
    dict(company="TransForm Shared Service Organization", role="Junior Support Analyst", status="rejected",
         date_applied="2026-09-17", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Paradigm Capital Group", role="Junior Technical Analyst (AI & Data Engineering)", status="rejected",
         date_applied="2026-09-17", resume_version=None,
         location="Toronto, ON", source="Glassdoor"),
    dict(company="County of Essex", role="Help Desk Analyst, IT Temporary (12-months)", status="rejected",
         date_applied="2026-09-12", resume_version=None,
         location="Essex, ON", source="Indeed"),
    dict(company="Wren Labs", role="Junior Mechanical Technician", status="rejected",
         date_applied="2026-09-12", resume_version=None,
         location="Oakville, ON", source="Glassdoor"),
    dict(company="Vincent Associates Inc.", role="Junior Analyst", status="rejected",
         date_applied="2026-09-12", resume_version=None,
         location="Toronto, ON", source="Glassdoor"),
    dict(company="Campbellford Memorial Hospital", role="IT Technical Analyst", status="rejected",
         date_applied="2026-09-07", resume_version=None,
         location="Campbellford, ON", source="Indeed"),
    dict(company="Kensington", role="Marketing Insights & Reporting Analyst", status="rejected",
         date_applied="2026-09-07", resume_version=None,
         location="Toronto, ON", source="Glassdoor"),
    dict(company="FIS immigration Services Inc.", role="Junior Data Analyst", status="rejected",
         date_applied="2026-09-07", resume_version=None,
         location="Brampton, ON", source="Glassdoor"),
    dict(company="TransForm Shared Service Organization", role="Support Analyst", status="rejected",
         date_applied="2026-09-07", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Cronos GrowCo", role="Quality Assurance Technician", status="rejected",
         date_applied="2026-08-22", resume_version=None,
         location="Kingsville, ON", source="Indeed"),
    dict(company="Kyndryl", role="Junior IT Analyst (Risk and Compliance)", status="rejected",
         date_applied="2026-08-22", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="Third Octet", role="IT Support Analyst", status="rejected",
         date_applied="2026-08-20", resume_version=None,
         location="Mississauga, ON", source="Indeed"),
    dict(company="Maarut Inc", role="Application Support Specialist - Intermediate", status="rejected",
         date_applied="2026-08-20", resume_version=None,
         location="Toronto, ON", source="Glassdoor"),
    dict(company="OSCAR Pro", role="Tier 1 Technical Support Analyst", status="rejected",
         date_applied="2026-08-20", resume_version=None,
         location="Remote", source="Glassdoor"),
    dict(company="Miratech Canada Corp.", role="Information Systems Analyst - Computer Systems", status="rejected",
         date_applied="2026-08-20", resume_version=None,
         location="Toronto, ON", source="Glassdoor"),
    dict(company="Warehousing & Distribution", role="Junior Systems Optimization Analyst", status="rejected",
         date_applied="2026-08-20", resume_version=None,
         location="Scarborough, ON", source="Glassdoor"),
    dict(company="Vollmer Inc.", role="IT Coordinator", status="rejected",
         date_applied="2026-08-20", resume_version=None,
         location="Windsor, ON", source="Glassdoor"),
    dict(company="ArcelorMittal Windsor", role="IT Software Developer", status="rejected",
         date_applied="2026-08-01", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="CGI", role="Data Analyst", status="rejected",
         date_applied="2026-08-01", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="Anchor Danly", role="Systems Analyst", status="rejected",
         date_applied="2026-07-18", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="BanQsi", role="Business Data Analyst", status="rejected",
         date_applied="2026-07-01", resume_version=None,
         location="Remote", source="Indeed"),
    dict(company="Orion Digital", role="Product Insights Analyst", status="rejected",
         date_applied="2026-07-01", resume_version=None,
         location="Remote", source="Indeed"),
    dict(company="Irving Tissue", role="Opportunities for Machine Operators", status="rejected",
         date_applied="2026-07-01", resume_version=None,
         location="Toronto, ON", source="Glassdoor"),
    dict(company="Design Stainless Steel Ltd", role="Admin Staff", status="rejected",
         date_applied="2026-07-01", resume_version=None,
         location="Etobicoke, ON", source="Glassdoor"),
    dict(company="LYNKED Inc.", role="Operations Support Specialist", status="rejected",
         date_applied="2026-07-01", resume_version=None,
         location="London, ON", source="Indeed"),
    dict(company="Questrade Financial Group", role="IT & Cyber Business Analyst", status="rejected",
         date_applied="2026-06-28", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="Sabre Limited", role="Help Desk Support Technician (L1)", status="rejected",
         date_applied="2026-06-28", resume_version=None,
         location="Greater Toronto Area, ON", source="Indeed"),
    dict(company="Eldis Group Partnership", role="Web Analytics Analyst", status="rejected",
         date_applied="2026-06-28", resume_version=None,
         location="Remote", source="Indeed"),
    dict(company="Daybar Industries Ltd", role="IT Administrator / Technical Support Analyst", status="rejected",
         date_applied="2026-06-28", resume_version=None,
         location="Brampton, ON", source="Indeed"),
    dict(company="Arzosoft", role="Part-time: Data Analytics, Data Entry, Disputes Analyst", status="rejected",
         date_applied="2026-06-25", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Franklin Empire Inc", role="Application Specialist - Factory Automation, Motion and Drives", status="rejected",
         date_applied="2026-06-11", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Marentette Services Incorporated", role="IT System Administrator", status="rejected",
         date_applied="2026-06-11", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Mayson Enterprises", role="PLC Programmer", status="rejected",
         date_applied="2026-06-07", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="InCycle Automation", role="Robotics Engineer/Tech", status="rejected",
         date_applied="2026-06-07", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Smith and Long", role="IT Support Specialist", status="rejected",
         date_applied="2026-06-07", resume_version=None,
         location="Etobicoke, ON", source="Indeed"),
    dict(company="Windsor Machine Group", role="Applications Integration Developer", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Southpoint Equipment", role="Accounting & Payroll Administrator", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Chatham-Kent, ON", source="Indeed"),
    dict(company="Novitech LLC", role="ILI Data Analyst Trainee", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Vaughan, ON", source="Indeed"),
    dict(company="Releady", role="Systems Support Analyst", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="BenYac Technologies Private Limited", role="Data Analyst", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="Quantum Lifecycle Partners LP", role="Application Support Analyst", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Brampton, ON", source="Indeed"),
    dict(company="COSCO SHIPPING Lines (Canada) Inc.", role="IT Support Analyst", status="rejected",
         date_applied="2026-06-01", resume_version=None,
         location="Mississauga, ON", source="Indeed"),
    dict(company="Cavalier Tool & Manufacturing", role="Engineering Feasibility Specialist", status="rejected",
         date_applied="2026-05-31", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Greg Monforton and Partners", role="Legal Assistant / Clerical Staff", status="rejected",
         date_applied="2026-05-31", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Fulger Transport", role="Administrative Clerk", status="rejected",
         date_applied="2026-05-31", resume_version=None,
         location="Essex, ON", source="Indeed"),
    dict(company="Build a Dream", role="Accounting Coordinator", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Globe Manufacturing LTD", role="Data Entry Specialist", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Legacy Personnel Solutions", role="Quality Inspector - Full Time", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="ZF Foxconn Chassis Modules", role="Plant Accountant", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Confidential", role="Accounting Administrator", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="NCCE Inc.", role="HR Clerk", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="ACS Canada Company", role="Technical Service Specialist", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Solari Recruiting", role="Office Administrator", status="rejected",
         date_applied="2026-05-30", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Citylitics", role="Data Solutions Analyst", status="rejected",
         date_applied="2026-05-29", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="Agility PR Solutions", role="Business Operations Analyst", status="rejected",
         date_applied="2026-05-29", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="FOTOERMINEIA DIGITAL MEDIA", role="Data Analyst", status="rejected",
         date_applied="2026-05-29", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Releady", role="Data and Reporting Analyst - Intermediate", status="rejected",
         date_applied="2026-05-29", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="TransForm Shared Service Organization", role="Support Analyst", status="rejected",
         date_applied="2026-05-27", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Releady", role="Junior Data Analyst", status="rejected",
         date_applied="2026-05-27", resume_version=None,
         location="Toronto, ON", source="Indeed"),
    dict(company="Confidential", role="Information Technologist", status="rejected",
         date_applied="2026-05-27", resume_version=None,
         location="Leamington, ON", source="Indeed"),
    dict(company="Manhall Consulting Services", role="Office Operations Coordinator", status="rejected",
         date_applied="2026-05-27", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Confidential", role="Part Time Office Administrator - Day Shift Hours", status="rejected",
         date_applied="2026-04-14", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Central Stampings Limited", role="Human Resource Clerk", status="rejected",
         date_applied="2026-04-13", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Termax LLC", role="Data Analyst & Processor", status="rejected",
         date_applied="2026-04-13", resume_version=None,
         location="Windsor, ON", source="Indeed"),
    dict(company="Jobright.ai", role="Customer Support Specialist, Entry Level", status="rejected",
         date_applied="2026-08-03", resume_version=None,
         location="Canada", source="Jobright.ai"),
    dict(company="Jobright.ai", role="Data Analyst, New Grad (Canada)", status="rejected",
         date_applied="2026-08-03", resume_version=None,
         location="Canada", source="Jobright.ai"),
    dict(company="Jobright.ai", role="Data Analyst, New Grad", status="rejected",
         date_applied="2026-08-03", resume_version=None,
         location="Canada", source="Jobright.ai"),
    dict(company="Jobright.ai", role="IT Help Desk Technician, Entry Level", status="rejected",
         date_applied="2026-08-03", resume_version=None,
         location="Canada", source="Jobright.ai"),
    dict(company="Jobright.ai", role="Technical Support / IT Help Desk, Entry Level", status="rejected",
         date_applied="2026-08-03", resume_version=None,
         location="Canada", source="Jobright.ai"),
    dict(company="Apple", role="CA-Technical Specialist", status="rejected",
         date_applied="2026-07-07", resume_version=None,
         location="London, ON", source="Jobright.ai"),
    dict(company="Legrand, North & Central America", role="Junior Business Analyst", status="rejected",
         date_applied="2026-10-01", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Tata Consultancy Services", role="ITSM Transition Analyst, Network Junior Engineer Jr", status="rejected",
         date_applied="2026-10-01", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Renewable Careers", role="Renewable Energy Engineer (Entry-Level)", status="rejected",
         date_applied="2026-09-28", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Qual IT Resources", role="Information Technology Specialist", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Soroc Technology", role="Datacenter Technician", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Insight Global", role="Data Center Engineer", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="InVision Staffing Services Inc.", role="Electronic Repair Technician", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Scarborough, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Sr. Technical Support Analyst", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="API Support Analyst", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Modern Technical Staffing Inc.", role="Controls Engineer", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="JAM CRM", role="Project Coordinator", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="WaterlooIT", role="Tier One Technical Support", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Kitchener, ON", source="LinkedIn"),
    dict(company="Enterprise Solutions Inc.", role="Tandem Java Developer", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="iPartner Consulting", role="Data Analyst with AWS - Toronto", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Raise", role="Data Quality Analyst", status="rejected",
         date_applied="2026-09-27", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Experis", role="Data Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Etobicoke, ON", source="LinkedIn"),
    dict(company="Precision Resource, Inc.", role="IT Help Desk Administrator", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Cambridge, ON", source="LinkedIn"),
    dict(company="Canpar Express", role="Application Support Technician", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Brampton, ON", source="LinkedIn"),
    dict(company="EXL", role="Business Analyst - Data Analysis & UAT Testing", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Hamilton, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="Automation Engineer [14423]", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="V2Soft", role="Hardware/Battery Test Automation Engineer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Insight Global", role="Administrative Associate", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Luxoft", role="Murex Support S4C", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Ampstek", role="SAP HCM Consultant", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Raise", role="Support Analyst - Trade Floor", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Stacktics", role="Google Analytics Specialist", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Tundra Technical Solutions", role="Power Platform Administrator", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="EnerSavings Inc", role="Project Coordinator - Solar Infrastructure", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Odyssey Global", role="Desktop Support Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="TPH Plumbing & Heating", role="Project Coordinator", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Ottawa, ON", source="LinkedIn"),
    dict(company="Global Technical Talent", role="Business Systems Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Experis Canada", role="Battery Test Project Engineer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Tekgence Inc", role="iOS Developer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Systematix", role="Technical Support Engineer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Zodiac Solutions, Inc", role="Offensive Security Engineer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Klaren", role="Tier 3 Support Technician", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Mindlance", role="Business Intelligence Consultant", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="US Tech Solutions", role="Data Management Analyst #26-23483", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Abacus Service Corporation", role="Project Engineer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="V2Soft", role="Project Engineer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Zobility", role="Project Engineer - Battery Testing & Validation", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="CIBC", role="Data Application Developer", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="CIBC", role="Business Systems Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="CIBC", role="Consultant, Business Systems Analysis", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="CIBC", role="Technical Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="TBWA\\Canada", role="Data Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="CIBC", role="Consultant, Reporting and Analytics", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="AppDirect", role="Growth Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="MEDFAR Clinical Solutions", role="Operations Coordinator - Technical Support", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Montreal, QC", source="LinkedIn"),
    dict(company="Tech-Nique Partners", role="IT Support Specialist", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Hamilton, ON", source="LinkedIn"),
    dict(company="Preston Phipps Inc", role="Building Automation Systems (BAS) Technician", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Infotek Consulting Inc.", role="System Support Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Wolseley Canada Inc.", role="Technical Support Analyst (Burlington, ON)", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Burlington, ON", source="LinkedIn"),
    dict(company="Adaria Vending Services Limited", role="IT Support Specialist", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Concord, ON", source="LinkedIn"),
    dict(company="Xodus Travel Services Inc.", role="Project Manager", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Trooh", role="Operations Analyst", status="rejected",
         date_applied="2026-09-20", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Tayco", role="Data Analyst (BI Specialist) - Contract", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="Etobicoke, ON", source="LinkedIn"),
    dict(company="Ready Systems Industries Inc.", role="PLC Programmer", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="Brantford, ON", source="LinkedIn"),
    dict(company="O-HIVE.AI", role="Product / Project Manager", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Niche Bakers Corp.", role="Production Data Analyst", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Plaza Premium Group", role="Business Intelligence Analyst", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="HCLTech", role="Meeting Room Services Support Analyst", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="London, ON", source="LinkedIn"),
    dict(company="Fengate Capital Management Ltd.", role="Financial Analyst, Reporting (Future Opportunities)", status="rejected",
         date_applied="2026-09-13", resume_version=None,
         location="Oakville, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Business Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="TekStaff IT Solutions", role="BI/ Data analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Dexian", role="IT Business analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="InVision Staffing Services Inc.", role="Quality Technician (Electronics)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Confidential", role="Solution Intelligence Analyst II - analytics-SQL & Databricks", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Alimentiv", role="Clinical Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Jobgether", role="Data Analyst - MARVEL Strike Force", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Thermon", role="Electrical Control Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Oakville, ON", source="LinkedIn"),
    dict(company="Aversan Inc.", role="Hardware Test Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Dexian", role="Electro Mechanical Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Ottawa, ON", source="LinkedIn"),
    dict(company="Hays", role="Field Technician (Junior & Level 1)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Professional Staffing", role="Controls Software Designer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Kitchener-Cambridge-Waterloo, ON", source="LinkedIn"),
    dict(company="Trylon", role="Dynamics 365 Business Central Developer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Elmira, ON", source="LinkedIn"),
    dict(company="PayCruit", role="Electronic Test Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Cambridge, ON", source="LinkedIn"),
    dict(company="Akkodis", role="Operational Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Waterloo, ON", source="LinkedIn"),
    dict(company="Jamieson Wellness Inc.", role="Project Manager", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Experis", role="IT Helpdesk", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Brampton, ON", source="LinkedIn"),
    dict(company="Kellow Recruiting", role="Jr. Automation Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Belleville, ON", source="LinkedIn"),
    dict(company="Essex Lake Group", role="Solution Intelligence Analyst II - analytics - SQL & Databricks", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Brainhunter Systems Ltd", role="Data BSA/ Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Options Consulting Solutions", role="Data Analyst PowerBI", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Jamesway", role="Manufacturing - Electrical Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Cambridge, ON", source="LinkedIn"),
    dict(company="Micronetbd Inc", role="Information Technology Project Coordinator", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="CIBC", role="Consultant, Data and AI Analytics", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Elections Ontario", role="Senior Research & Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="North York, ON", source="LinkedIn"),
    dict(company="CIBC", role="Senior Endpoint Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="InVision Staffing Services Inc.", role="Electronic Test Technician (PCB)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Dexian", role="Business System Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Notified", role="Associate Client Support Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="BeachHead", role="Junior Power BI Analyst / Developer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Infotek Consulting Inc.", role="Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Dexian", role="Reporting Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Vinebrook Technology", role="Information Technology Support Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Tekgence Inc", role="Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Experis", role="Information Technology Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Milton, ON", source="LinkedIn"),
    dict(company="Citation Canada", role="Help Desk Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="London, ON", source="LinkedIn"),
    dict(company="Tundra Technical Solutions", role="Systems Engineering Operations Support", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Cambridge, ON", source="LinkedIn"),
    dict(company="Systematix", role="Electrical Engineering Technologist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Vaughan, ON", source="LinkedIn"),
    dict(company="Richards-Wilcox Canada", role="IT Support", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="J&M Group", role="Technical Support Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Alpha Controls & Instrumentation Inc.", role="Field Service Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Veem", role="Technical Support Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="TechDoQuest", role="Data Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Jobgether", role="Technical Support Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="HiredBuddy", role="Site Reliability Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="INVIRO Engineered Systems Ltd.", role="Junior Project Coordinator", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Scarborough, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Municipality of Port Hope", role="Information Technology Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Port Hope, ON", source="LinkedIn"),
    dict(company="Synechron", role="Production Support Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Artemis", role="Business Intelligence Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Renewable Careers", role="Entry-Level Analyst (Sustainability)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="SS&C Technologies", role="Client Services Analyst I", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Flexis IT", role="IT Helpdesk Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Millennium Software and Staffing Inc", role="Business Systems Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Cornerstone Building Brands", role="IT Operations Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Calgary, AB", source="LinkedIn"),
    dict(company="MatchBox Consulting Group", role="Data Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Newmarket, ON", source="LinkedIn"),
    dict(company="HISH IT SERVICES", role="Business Intelligence Developer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="John Brooks", role="Technical Support Representative", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Charger Logistics Inc.", role="Cloud Support Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Brampton, ON", source="LinkedIn"),
    dict(company="Foray Enterprises Inc.", role="PLC, Robotics & Automation Service Technician", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Kingsville, ON", source="LinkedIn"),
    dict(company="Infotek Consulting Inc.", role="RPA Developer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Architecttura Inc., Architects", role="HVAC Engineer - Building Systems / MEP", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="WaveRyde Instruments", role="Autonomous Systems Engineer - Quantum Sensors", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Waterloo, ON", source="LinkedIn"),
    dict(company="Deep Trekker Inc.", role="IT Helpdesk Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Kitchener, ON", source="LinkedIn"),
    dict(company="SecureRx Technologies Inc.", role="Business Intelligence Analyst (Entry-Level), Healthcare SaaS", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Ontario, Canada", source="LinkedIn"),
    dict(company="Vista Solutions Inc.", role="Machine Vision Engineer (MVE)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="LER TechForce", role="Mechanical Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Zobility", role="Powertrain Calibration Engineer (OBD, INCA, MATLAB, Simulink)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="Battery Pack Test Engineer [14397]", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="LER TechForce", role="Battery Test Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Vista Solutions Inc.", role="Machine Vision Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Abacus Service Corporation", role="Battery Management Systems Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Hays", role="Analyst, Parking Development", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Metergy Solutions", role="Business Intelligence Analyst", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="SDFX Studios", role="Systems Engineer, Associate", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Echoworx", role="Help Desk Support Specialist", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="goeasy Ltd.", role="Insights Analyst (Operations & Analytics)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="SHEIN", role="Data Analyst (Open to New Grads)", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Vaughan, ON", source="LinkedIn"),
    dict(company="Gauge Rite Inc.", role="Program Manager - Automotive Fixtures", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Tecumseh, ON", source="LinkedIn"),
    dict(company="LanceSoft, Inc.", role="Powertrain Engine OBD Calibration Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Collabera", role="Battery Pack Test Engineer", status="rejected",
         date_applied="2026-09-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Nexus Energy Inc.", role="Junior Settlements Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Altis", role="Business Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Abacus Service Corporation", role="Battery Management Systems Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Ampstek", role="Business / Functional Analyst (Global Account Transfers and Liquidity Management)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Punt", role="Business Intelligence Analyst, Player Analytics", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="United States", source="LinkedIn"),
    dict(company="Genpact", role="Service Desk Specialist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="ValueMomentum", role="Service Desk Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Galactic Minds INC", role="Product Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Syncredible Solutions", role="Data Scientist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="AspiringIT", role="Junior Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Renewable Careers", role="Graduate Analyst (Sustainability)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Data Analyst - SQL data mapping, transformation & schema structure (Banking exp Must)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="Recruiter", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="LER TechForce", role="Studio Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="EPITEC", role="ROBOT PROGRAMMER A", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="V2Soft", role="Design Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Zobility", role="Battery Simulation Engineer | MATLAB/Simulink | 0D/1D Battery Modeling & Simulation", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Jamieson Wellness Inc.", role="Continuous Improvement Associate", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="RGBSI", role="Computer Numerical Control Machinist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="Systems Controls Engineer [14377]", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Zobility", role="Propulsion Systems Controls Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="V2Soft", role="Powertrain Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Experis Canada", role="Battery Management Systems Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="KYYBA Inc", role="Powertrain calibration Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Canadian Executive Search Group", role="Controls Designer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Zobility", role="Battery Test & Validation Engineer (EV Battery Pack Systems)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="PLC Programmer [14217]", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Collabera", role="Battery Simulation Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="DuroByte Inc.", role="Automation Controls Specialist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="V2Soft", role="Battery Management Systems Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Nachi America Inc.", role="Robotics Field Service Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Alquemy Search & Consulting", role="I.T. Project Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Flexstaf I.T. Inc.", role="Junior Business Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="E-Solutions", role="Business Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Trapeze Group", role="Application Support Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Resonaite", role="Service Desk Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Data Analyst - SQL data mapping, transformation & schema structure", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="A.W. Hooker Associates Ltd.", role="Office Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Oakville, ON", source="LinkedIn"),
    dict(company="Spait Infotech", role="Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Vortex Group of Companies", role="IT Help Desk Technician", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Astreya", role="IT Inventory Technician / IT Support / IT Helpdesk (3 months contract)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Canarm Ltd.", role="Data Coordinator - Engineering", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Brockville, ON", source="LinkedIn"),
    dict(company="Aliant Resources", role="IT Technician", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="IntelliPro", role="Information Technology Project Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Micronetbd Inc", role="Information Technology Project Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="EM Dynamics", role="IT Support and Technology Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Scarborough, ON", source="LinkedIn"),
    dict(company="DuroByte Inc.", role="Automation Program Manager", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Net2Source (N2S)", role="Design Verification Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Ontario, Canada", source="LinkedIn"),
    dict(company="Systematix", role="Automation Developer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Vaughan, ON", source="LinkedIn"),
    dict(company="Millennium Software and Staffing Inc", role="Automation Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="SPECTRAFORCE", role="Information Technology Business Consultant", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="US Tech Solutions", role="#26-16852 Technical Support Specialist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="London, ON", source="LinkedIn"),
    dict(company="Integra Recruiters", role="Maintenance Technician", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Scarborough, ON", source="LinkedIn"),
    dict(company="Martinrea International", role="Robot Technician", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Ridgetown, ON", source="LinkedIn"),
    dict(company="Tata Consultancy Services", role="Data Engineer - Azure", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="SearchLabs", role="Electrical Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="TechDoQuest", role="Electromagnetic Compatibility Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="InVision Staffing Services Inc.", role="Electronics Test Technician (PCB)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Pacer Group", role="Workfusion RPA Developer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="ALTEN Canada", role="Power System Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Confidential", role="PLC Programmer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="Controls Engineer [14274]", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="iSoftStone", role="IT Service Desk Technician (L1) - Warehouse Operations", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Phoenix Search Group Inc.", role="Electrician - controls specialist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Etobicoke, ON", source="LinkedIn"),
    dict(company="Hays", role="Intelligent Automation Developer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Forge Consulting Group", role="Control Designer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Cullerton Group", role="Controls Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Detroit Metropolitan Area", source="LinkedIn"),
    dict(company="Rise Technical", role="Electrical Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Brampton, ON", source="LinkedIn"),
    dict(company="Recurrent Energy", role="Systems Performance Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Kitchener, ON", source="LinkedIn"),
    dict(company="PreCon", role="Industrial Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Woodstock, ON", source="LinkedIn"),
    dict(company="Collabera", role="Project Management Office (PMO) - Automotive Industry", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="V2Soft", role="Project Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="ALTEN Canada", role="Industrial Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Ontario, Canada", source="LinkedIn"),
    dict(company="SmartHire Human Capital Solutions", role="Service Technician", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Leamington, ON", source="LinkedIn"),
    dict(company="Avetix Engineering", role="Test Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Confidential", role="Electrical Engineer - Power", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Harvey Nash", role="Technical Support Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Artech L.L.C.", role="Calibration Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Waterloo, ON", source="LinkedIn"),
    dict(company="Gerrits Engineering Limited", role="Electrical Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Barrie, ON", source="LinkedIn"),
    dict(company="DXC Technology", role="Junior Microsoft 365 Administrator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="MEDA Engineering & Technical Services", role="Project Management Coordinator [14375]", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Dexterra Group", role="Technical Solutions Specialist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Great Value Hiring", role="Electrical Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="RedCompass Labs", role="First Line Support", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Dexian", role="Application Support Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="TROIS Collective", role="Electrical Engineer (Intermediate)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Ontario, Canada", source="LinkedIn"),
    dict(company="V2Soft", role="Automotive Project Coordinator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="AspiringIT", role="Technical Support Specialist", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="PrideNow", role="Program Manager", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Hays", role="Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="LTIMindtree", role="Data Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Spitfire Recruiting Inc.", role="Technical Support Representative (Tier 1)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Barrie, ON", source="LinkedIn"),
    dict(company="Pacer Group", role="Business Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Tundra Technical Solutions", role="Junior IT Administrator", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Brunel", role="Junior Information Technology Support Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Direct IT Recruiting Inc.", role="Junior IT Vendor Management Analyst (1866)", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="TechDoQuest", role="System Support Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="E-IT", role="Sr. EUC Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="MaximaTek", role="Data Analyst", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Ontario, Canada", source="LinkedIn"),
    dict(company="CoberonChronos", role="Field Services Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Box Labs", role="Pharmacy Technician / Software Trainer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Agility IT", role="Data Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Spectrum Dynamics Medical", role="Field Services Engineer", status="rejected",
         date_applied="2026-08-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Crossing Hurdles", role="Data Engineer | Remote", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Robert Half", role="Business Intelligence Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Cambridge, ON", source="LinkedIn"),
    dict(company="Philip Morris International", role="BI Developer - Fixed Term Contract", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="FDM Group", role="Junior Business Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="hireVouch", role="Technical Support Specialist", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Richmond Hill, ON", source="LinkedIn"),
    dict(company="Helic & Co", role="Junior Software Developer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="TechDoQuest", role="Production Support Specialist", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Spait Infotech", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="SPECTRAFORCE", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Helic & Co", role="Junior Data Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Crossing Hurdles", role="Audio Transcription Specialist", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Vista Solutions Inc.", role="Machine Vision Engineer (MVE)", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Brooksource", role="Technical Business Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Science North & Dynamic Earth", role="Technical Specialist", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Greater Sudbury, ON", source="LinkedIn"),
    dict(company="Delpath", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Robert Half", role="Power BI Developer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="TC Transcontinental", role="Continuous Improvement Advisor", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Aurora, ON", source="LinkedIn"),
    dict(company="Iris Software Inc.", role="Production Support Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Lorven Technologies Inc.", role="Production Support Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="HISH IT SERVICES", role="Business System Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Portfolio Aid Inc.", role="Business System Analyst I", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="DVTEST", role="Integration Technician", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Pickering, ON", source="LinkedIn"),
    dict(company="Shopify", role="Overnight Merchant Support Advisor, Canada", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Aversan Inc.", role="Junior Hardware Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="GFL Environmental Inc.", role="Business Systems Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Vaughan, ON", source="LinkedIn"),
    dict(company="Jobgether", role="Support AI Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Experis", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Etobicoke, ON", source="LinkedIn"),
    dict(company="Insight Global", role="Technical Support Specialist", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="St. Jacobs, ON", source="LinkedIn"),
    dict(company="Crossing Hurdles", role="Data Analyst (Excel)", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="General Dynamics Mission Systems-Canada", role="Junior Systems Engineer - Networking", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Ottawa, ON", source="LinkedIn"),
    dict(company="Iris Software Inc.", role="Application Support Engineer (Trading Exp)", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Kaizen Technologies", role="PL/SQL Developer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="StarIC", role="Semiconductor EDA/CAD/IT Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="KTek Resourcing", role="Technical Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Miipe Quality Solutions", role="Sr QA Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Mindlance", role="System Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Insight Global", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Helic & Co", role="Junior Software Developer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Crossing Hurdles", role="Computer Systems Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Helic & Co", role="Associate Software Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Epsilon Solutions Ltd.", role="BSA-SQL", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Robertson & Company Ltd.", role="IT - Data Analytics", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Iris Software Inc.", role="Production Services Support Analyst (Capital Markets / Fixed Income)", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Mastercard Foundation Asset Management", role="Information Technology Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Enterprise Solutions Inc.", role="Application Support Analyst (Mainframe/AS400)", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Tata Consultancy Services", role="Data Quality Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Mastercard Foundation Asset Management", role="Data & Analytics Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Helic & Co", role="Junior Data Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Tech People 247", role="Information Technology Support Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Timmins, ON", source="LinkedIn"),
    dict(company="Infinite Investment Systems", role="System Support Associate", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="JAM CRM", role="Project Coordinator", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Dimensionless Technologies", role="Data Engineer - Capital Markets", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Teranet Inc.", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Trillium Health Partners", role="Associate, Systems & Data", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="Robert Half", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Insight Global", role="Report Developer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Encore Technical Solutions Inc.", role="Junior Data Engineer - New Grad", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="RGBSI", role="Service Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Zobility", role="Wire Harness Design and Release Engineer (Automotive)", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Windsor, ON", source="LinkedIn"),
    dict(company="Helic & Co", role="Junior Data Engineer", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Apptoza Inc.", role="Data Analyst", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Citation Canada", role="Technology Intern", status="rejected",
         date_applied="2026-07-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Red Oak Technologies", role="Information Technology Support Specialist", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Connexall", role="Technical Support Specialist I", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Pacer Group", role="Production Support Specialist", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Robert Half", role="Information Technology Support Specialist", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn"),
    dict(company="Experis", role="Operation IT Support", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Alliston, ON", source="LinkedIn"),
    dict(company="Fusion Homes", role="IT Analyst", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Guelph, ON", source="LinkedIn"),
    dict(company="GTA GSM", role="Technical Operations Analyst", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Mississauga, ON", source="LinkedIn"),
    dict(company="BrightIT", role="Service Desk Engineer L1", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="MGI Construction Corp.", role="Information Technology Coordinator", status="rejected",
         date_applied="2026-06-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="TekStaff IT Solutions", role="IT Analyst", status="rejected",
         date_applied="2026-05-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="ASUS", role="Office Administrator", status="rejected",
         date_applied="2026-04-04", resume_version=None,
         location="Markham, ON", source="LinkedIn"),
    dict(company="Crossing Hurdles", role="Human Data Assistant", status="rejected",
         date_applied="2026-04-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="Asset Inventories", role="IT support specialist", status="rejected",
         date_applied="2026-04-04", resume_version=None,
         location="Toronto, ON", source="LinkedIn"),
    dict(company="Insight Global", role="Support Analyst", status="rejected",
         date_applied="2026-02-04", resume_version=None,
         location="Canada", source="LinkedIn"),
    dict(company="GreenShield", role="Financial Analyst, Enterprise Expense", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes="Cover letter drafted; confirm whether actually submitted."),
    dict(company="Affirm", role="Analytics Lead, Full Stack (Collections & Recoveries)", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes=None),
    dict(company="Bell", role="2027 Graduate Program - Customer Experience", status="screening",
         date_applied="2026-09-27", resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes="Advanced to pre-screening video questionnaire; completed Sep 30, 2026."),
    dict(company="Intelcom", role="Package Handler - Warehouse Clerk", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes=None),
    dict(company="Moneris", role="Business Data Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="KEV Group", role="Technical Support Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="KPMG Canada", role="Bilingual One Port User Support Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes=None),
    dict(company="Harris Computer", role="Desktop Deployment Specialist", status="rejected",
         date_applied=None, resume_version=None,
         location="Ottawa, ON", source="LinkedIn", notes=None),
    dict(company="Euna Solutions", role="Associate Support Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Oakville, ON", source="LinkedIn", notes=None),
    dict(company="ICES", role="Management Information Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Turner Fleischer", role="Project Coordinator", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Staples Canada", role="Analyst - Space Planning", status="rejected",
         date_applied=None, resume_version=None,
         location="Richmond Hill, ON", source="LinkedIn", notes=None),
    dict(company="Durham Region (The Regional Municipality of Durham)", role="Data Analysis Coordinator", status="rejected",
         date_applied=None, resume_version=None,
         location="Whitby, ON", source="LinkedIn", notes=None),
    dict(company="OXARO Inc.", role="Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Ottawa, ON", source="LinkedIn", notes=None),
    dict(company="Pet Valu", role="Supply Chain BI Solutions Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Markham, ON", source="LinkedIn", notes=None),
    dict(company="Hydro Ottawa", role="Customer Experience and Process Improvement Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Ottawa, ON", source="LinkedIn", notes=None),
    dict(company="Bimbo Canada", role="Sales Analyst, Tools & Technology", status="rejected",
         date_applied=None, resume_version=None,
         location="Etobicoke, ON", source="LinkedIn", notes=None),
    dict(company="QuadReal Property Group", role="Analyst, Sustainability", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Armstrong World Industries", role="CAD Technician I", status="rejected",
         date_applied=None, resume_version=None,
         location="Mississauga, ON", source="LinkedIn", notes=None),
    dict(company="Entegris", role="Engineering Technician, New Product Development", status="rejected",
         date_applied=None, resume_version=None,
         location="Scarborough, ON", source="LinkedIn", notes=None),
    dict(company="CAMH", role="Data Analyst - Data & Insights", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="MNP", role="Consultant, Microsoft Power Platform", status="rejected",
         date_applied=None, resume_version=None,
         location="Ottawa, ON", source="LinkedIn", notes=None),
    dict(company="AtkinsRealis", role="Project Coordinator", status="rejected",
         date_applied=None, resume_version=None,
         location="Kincardine, ON", source="LinkedIn", notes=None),
    dict(company="Mirion Technologies", role="Quality Engineering Technologist (Mechanical)", status="rejected",
         date_applied=None, resume_version=None,
         location="Cambridge, ON", source="LinkedIn", notes=None),
    dict(company="LG Electronics Canada", role="Price, Promotion & Trade Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="North York, ON", source="LinkedIn", notes=None),
    dict(company="BBA Consultants", role="Junior Electrical Engineering Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Concord, ON", source="LinkedIn", notes=None),
    dict(company="Integra", role="Tech I - Electrical Assembly (Afternoon Shift)", status="rejected",
         date_applied=None, resume_version=None,
         location="Harrow, ON", source="LinkedIn", notes=None),
    dict(company="TalentSphere Staffing Solutions", role="Building Automation Systems (BAS) Engineer/Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Essity Aktiebolag", role="Sales Reporting Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Oakville, ON", source="LinkedIn", notes=None),
    dict(company="Thermo Fisher Scientific", role="Electronic Controls Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Mississauga, ON", source="LinkedIn", notes=None),
    dict(company="Gowling WLG", role="Business Analyst, Enterprise Project Management Office", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Convergint - Canada", role="Automation Systems Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Brantford, ON", source="LinkedIn", notes=None),
    dict(company="Trane Technologies", role="Controls Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Ottawa, ON", source="LinkedIn", notes=None),
    dict(company="PartnerRE Ltd.", role="Business Data Analyst - Reporting and Audit", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Encore Canada", role="Financial Data Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Brampton, ON", source="LinkedIn", notes=None),
    dict(company="Ainsworth Inc", role="BAS Specialist", status="rejected",
         date_applied=None, resume_version=None,
         location="Mississauga, ON", source="LinkedIn", notes=None),
    dict(company="Scotiabank", role="Technical Support Analyst, Applications", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="TELUS Health", role="Cloud & Infrastructure Specialist", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Magna International", role="Controls Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Penetanguishene, ON", source="LinkedIn", notes=None),
    dict(company="SCS Consulting Group Ltd.", role="Junior Design Engineer", status="rejected",
         date_applied=None, resume_version=None,
         location="Markham, ON", source="LinkedIn", notes=None),
    dict(company="Mirion Technologies", role="Quality Assurance Technologist/Technician (Electronics)", status="rejected",
         date_applied=None, resume_version=None,
         location="Cambridge, ON", source="LinkedIn", notes=None),
    dict(company="smartTrade Technologies", role="Support Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Minth North America, Inc.", role="Metrologist/Laboratory Coordinator", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes=None),
    dict(company="NextStar Energy", role="Equipment Electrician", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes=None),
    dict(company="Perseus Group, Constellation Software", role="Desktop Support Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Markham, ON", source="LinkedIn", notes=None),
    dict(company="GHD Northern Hemisphere", role="Graduate Engineering Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Markham, ON", source="LinkedIn", notes=None),
    dict(company="IMAX", role="Analyst, Financial Reporting", status="rejected",
         date_applied=None, resume_version=None,
         location="Mississauga, ON", source="LinkedIn", notes=None),
    dict(company="Green Infrastructure Partners", role="CAD Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes=None),
    dict(company="Global Excel Management Inc", role="Data Developer II", status="rejected",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="LinkedIn", notes=None),
    dict(company="Barton Malow Company", role="Project Coordinator", status="rejected",
         date_applied=None, resume_version=None,
         location="Cambridge, ON", source="LinkedIn", notes=None),
    dict(company="Diebold Nixdorf, Incorporated", role="Field Service Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Owen Sound, ON", source="LinkedIn", notes=None),
    dict(company="IAMGOLD", role="Instrumentation Apprentice", status="rejected",
         date_applied=None, resume_version=None,
         location="Gogama, ON", source="LinkedIn", notes=None),
    dict(company="FDM Group", role="Junior Information Technology Consultant", status="rejected",
         date_applied=None, resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn", notes=None),
    dict(company="Primoris Services Corporation", role="Service Desk Technician", status="rejected",
         date_applied=None, resume_version=None,
         location="Burlington, ON", source="LinkedIn", notes=None),
    dict(company="KFC", role="Bilingual IT Service Desk Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Vaughan, ON", source="LinkedIn", notes=None),
    dict(company="FDM Group", role="Production Support Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Greater Toronto Area, ON", source="LinkedIn", notes=None),
    dict(company="Astra-North Infoteck Inc.", role="Production Support Analyst (Unix/Linux, SQL, Control-M, ITRS Geneos, Capital Markets)", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="H&M", role="Commercial Business Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="Charger Logistics Inc.", role="Junior Cloud Engineer", status="rejected",
         date_applied=None, resume_version=None,
         location="Brampton, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="Axxima", role="Junior IT administrator", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="Fusion Homes", role="IT Analyst", status="rejected",
         date_applied=None, resume_version=None,
         location="Guelph, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="Direct IT Recruiting Inc.", role="ITSM Analyst (1874)", status="rejected",
         date_applied=None, resume_version=None,
         location="Toronto, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="Fidus Systems", role="Information Technology Support Generalist", status="rejected",
         date_applied=None, resume_version=None,
         location="Ottawa, ON", source="LinkedIn", notes="Left as a draft and never finished submitting; posting has since closed."),
    dict(company="FDM Group", role="Change and Transformation Program", status="offer",
         date_applied="2026-06-15", resume_version=None,
         location="Toronto, ON", source="FDM recruiting process", notes="Completed all four recruitment stages with positive assessments. Contingent offer, on the waitlist since early August 2026, no confirmed start date. Recruiter transitioned from Taj Raleigh to Mitchell Sadler (late Aug 2026), who checks in every 3-4 weeks."),
    dict(company="Welcome Centre Shelter for Women & Families", role="Social Enterprise Project Manager", status="ghosted",
         date_applied=None, resume_version=None,
         location="Windsor, ON", source="Direct (prior placement)", notes="Invited to interview, but the role requires a driver's license, which he does not have, and the offered dates conflicted with travel abroad. No response since."),
    dict(company="Canada Revenue Agency", role="IT Developer (CS-01)", status="screening",
         date_applied=None, resume_version=None,
         location="Canada", source="GC Jobs", notes="Invited to a written assessment, window Sep 25 to 30, 2026."),
]


def run():
    init_db()
    with get_conn() as conn:
        n = conn.execute("SELECT COUNT(*) AS n FROM applications").fetchone()["n"]
    if n:
        print(f"Database already has {n} applications, skipping seed.")
        return
    for item in DEMO:
        crud.create_application({**item,
            "status": item.get("status", "applied"),
            "date_applied": item.get("date_applied"),
            "follow_up_date": item.get("follow_up_date"),
            "resume_version": item.get("resume_version"),
            "job_url": item.get("job_url"),
            "location": item.get("location"),
            "source": item.get("source"),
            "notes": item.get("notes")})
    print(f"Seeded {len(DEMO)} applications.")


if __name__ == "__main__":
    run()
